package com.thunder.lifecare.GreenDao.daomodel;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thunder.lifecare.GreenDao.daomodel.HomeCategory;
import com.thunder.lifecare.GreenDao.daomodel.Inventory;
import com.thunder.lifecare.GreenDao.daomodel.HomeRootObject;

import com.thunder.lifecare.GreenDao.daomodel.HomeCategoryDao;
import com.thunder.lifecare.GreenDao.daomodel.InventoryDao;
import com.thunder.lifecare.GreenDao.daomodel.HomeRootObjectDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeCategoryDaoConfig;
    private final DaoConfig inventoryDaoConfig;
    private final DaoConfig homeRootObjectDaoConfig;

    private final HomeCategoryDao homeCategoryDao;
    private final InventoryDao inventoryDao;
    private final HomeRootObjectDao homeRootObjectDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeCategoryDaoConfig = daoConfigMap.get(HomeCategoryDao.class).clone();
        homeCategoryDaoConfig.initIdentityScope(type);

        inventoryDaoConfig = daoConfigMap.get(InventoryDao.class).clone();
        inventoryDaoConfig.initIdentityScope(type);

        homeRootObjectDaoConfig = daoConfigMap.get(HomeRootObjectDao.class).clone();
        homeRootObjectDaoConfig.initIdentityScope(type);

        homeCategoryDao = new HomeCategoryDao(homeCategoryDaoConfig, this);
        inventoryDao = new InventoryDao(inventoryDaoConfig, this);
        homeRootObjectDao = new HomeRootObjectDao(homeRootObjectDaoConfig, this);

        registerDao(HomeCategory.class, homeCategoryDao);
        registerDao(Inventory.class, inventoryDao);
        registerDao(HomeRootObject.class, homeRootObjectDao);
    }
    
    public void clear() {
        homeCategoryDaoConfig.clearIdentityScope();
        inventoryDaoConfig.clearIdentityScope();
        homeRootObjectDaoConfig.clearIdentityScope();
    }

    public HomeCategoryDao getHomeCategoryDao() {
        return homeCategoryDao;
    }

    public InventoryDao getInventoryDao() {
        return inventoryDao;
    }

    public HomeRootObjectDao getHomeRootObjectDao() {
        return homeRootObjectDao;
    }

}
